# This workflow will do a clean installation of the dependencies and builds the source code
# Push will only be available at the branches 
name: push
       
on: push

jobs:
  push_actions: 
    runs-on: ubuntu-latest
    steps:
      # Checkouts out of the repo
      - name: Checkout repo
        uses: actions/checkout@v3
            
      # Install the dependencies  
      - name: Install dependencies
        run: npm install

      # # Runs the tests 
      # - name: Run test
      #   run: SERVER_SECRET="${{ secrets.SERVER_SECRET }}" npm test

